# Generated by Django 3.1.2 on 2020-11-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201104_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ['date'], 'verbose_name_plural': 'Analysis'},
        ),
    ]
